### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mboelen** [0x3curity/TheDoc#1]
Thanks for your tool. I have added your tool to linuxsecurity.expert: [TheDoc](https://linuxsecurity.expert/tools/thedoc/)

Question: what is the license for this tool?

Suggestion: hashcat in the GitHub description is missing a 't'

**Comment by ViniciusRio** [comment]
I did not find a guide to use, I actually could not even open the program

**Comment by OffXec** [comment]
The tools use is very simple, it's made in BASH shell scripting,
use: bash theDoc.sh 
or
chmod +x ./theDoc.sh

**Comment by OffXec** [comment]
README.md has been modified and typos fixed(Thank you for pointing that out, lol). And as far as licensing goes, tbh im not use to having to use a license when it comes to developing.

**Comment by mboelen** [comment]
@0x3curity the lack of a license could limit the number of people that actually can use your tool or contribute. For this kind of projects, it is common to see MIT, GPLv2 or GPLv3, or Apache 2.0 license.

Would be great if you could choose one.

**Comment by OffXec** [comment]
Thanks! I'll definitely look in to that and update my repos.

**Comment by ViniciusRio** [comment]
I got it, it's working. Now I can use

Thanks!
